[package]
name = "email_lambda"
version = "0.1.0"
authors = ["Bryan Swift <bryan@bryanjswift.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
email_shared = { version = "0.1.0", path = "../email_shared" }
lambda_runtime = "0.2.1"
lazy_static = "1.4.0"
log = "0.4.11"
rusoto_core = "0.45.0"
rusoto_dynamodb = "0.45.0"
rusoto_sqs = { version = "0.45.0", features = [ "deserialize_structs" ] }
serde = "1.0.115"
serde_json = "1.0.57"
simplelog = "0.8.0"
tokio = { version = "0.2.22", features = ["macros", "rt-core"] }
